task_analise_scholar:
  description: > 
    Analisar o perfil do Google Scholar usando a URL fornecida ({profile_url}) e extrair informações importantes como 
    área principal de pesquisa, artigos relevantes e número de citações.
  expected_output: > 
    Um JSON contendo:
    - Principal área de pesquisa do autor
    - URLs de até 5 artigos relevantes
    - Número total de citações
  agent: analista_scholar

task_busca_perfil:
  description: >
    Buscar o perfil do pesquisador '{researcher_name}' no Google Scholar usando exatamente este nome.
    Não tente outros nomes ou variações.
  expected_output: >
    A URL exata do perfil do Google Scholar do pesquisador.
  agent: buscador_scholar


